sudo: required

#language: php
env: 
    ->
    container_id=$(mktemp)

services:
  - docker

before_install:
  - docker pull nsidhaye/msphpsql 

  
script:
  - docker run -d -t -p 4080:80 nsidhaye/msphpsql apache2ctl start > "${container_id}"
  - phantomjs testrunner.js 
  - phantomjs testPhantom.js
  - docker ps -a  
  - docker stop "$(cat ${container_id})"
  
notifications:
  email: false
