sudo: false

#language: php

services:
  - docker

before_install:
  #- docker pull nsidhaye/msphpsql 
  - docker run -d -p 127.0.0.1:80:80 nsidhaye/msphpsql ps -a


script:
  - phantomjs testrunner.js 
  - phantomjs testPhantom.js
