sudo: required

#language: php
env: 
    ->
    container_id=$(mktemp)

services:
  - docker

before_install:
  - docker pull nsidhaye/msphpsql 
  - docker run -td -p 4080:80 nsidhaye/msphpsql > "${container_id}"
  
script:
  - phantomjs testPhantom.js
  - phantomjs testrunner.js 
  - phantomjs phpinfo.js 
  - docker ps -a  
  - docker stop "$(cat ${container_id})"
  - docker ps -a  
  - docker rm "$(cat ${container_id})"
  
notifications:
  email: false
